In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
pip install --upgrade pip


   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----------------- ---------------------- 0.8/1.8 MB 7.8 MB/s eta 0:00:01
   ---------------------- ----------------- 1.0/1.8 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 2.9 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 25.0.1
    Uninstalling pip-25.0.1:
      Successfully uninstalled pip-25.0.1


In [2]:
import numpy as np

In [11]:
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [10]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
#arrays of zeros
zeros=np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
#array of ones
ones=np.ones((4,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [30]:
#array of randoms
ones=np.random.random((4,4))
print(ones)


[[0.95325386 0.80688248 0.61874816 0.33013146]
 [0.33427675 0.02635143 0.09433102 0.32543782]
 [0.23796444 0.28318685 0.34305289 0.92100892]
 [0.79855678 0.50244397 0.56916971 0.38891885]]


In [25]:
#identity matrix
identity=np.eye(4)
print(identity

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
#Array with arange of values
range_arr=np.arange(0,10,2) #start,stpe,step
print(range_arr)

[0 2 4 6 8]


In [32]:
arr2=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr2.shape)
print("Size:",arr2.size)
print("Data type :",arr2.dtype)
print("Number of dimensions:",arr2.ndim)



Shape: (2, 3)
Size: 6
Data type : int64
Number of dimensions: 2


[]


In [41]:
list1=[10,20,30,40]
list2=[50,60,70,80]
c=[]
for i in range(len(list1)):
    c.append(list1[i]+list2[i])
print(c)

        

[60, 80, 100, 120]


In [43]:
a=np.array([10,20,30,40])
b=np.array([50,60,70,80])
print(a+b)
print(a*b)
print(a*2)

[ 60  80 100 120]
[ 500 1200 2100 3200]
[20 40 60 80]


In [49]:
a=np.array([[1,2,3],[4,5,6],[3,6,7]])
b=np.array([[7,8,9],[1,9,2],[4,6,8]])


res=np.dot(a,b)
print(res)



[[ 21  44  37]
 [ 57 113  94]
 [ 55 120  95]]


In [50]:
#broadcasting
a=np.array([1,2,3])
b=2
print(a+b)

[3 4 5]


In [52]:
#universal functions
a=np.array([1,2,3])
print(np.exp(a))
print(np.sqrt(a))
print(np.log(a))

[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]


In [55]:
a=np.array([1,2,3])
print(a)
print("Sum:",np.sum(a))
print("Mean:",np.mean(a))
print("Standard Deviation",np.std(a))
print("Max",np.max(a))
print("Min",np.min(a))

[1 2 3]
Sum: 6
Mean: 2.0
Standard Deviation 0.816496580927726
Max 3
Min 1


In [56]:
a=np.array([1,2,3,4,5,6])
print(a.reshape(2,3))


[[1 2 3]
 [4 5 6]]


In [3]:
#stacking
a=np.array([1,2])
b=np.array([4,5])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2]
 [4 5]]
[1 2 4 5]


In [4]:
arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [5]:
#view shares memory
arr=np.array([1,2,3])
view=arr.view()
view[0]=10
print(arr)
#Copy does not share memory
copy=arr.copy()
copy[0]=10
print(arr)

[10  2  3]
[10  2  3]


In [12]:
#task
a=np.array([10,20,30,40,50])
print(a)
print("Shape:",a.shape)
print("Size:",a.size)
print("Data type :",a.dtype)
print("Number of dimensions:",a.ndim)
rand=np.random.random((3,3))
print(rand)
print("Shape:",rand.shape)
print("Size:",rand.size)
print("Data type :",rand.dtype)
print("Number of dimensions:",rand.ndim)
b=5
print(f"adding 5 to each element of array {a}:\n",a+b)


[10 20 30 40 50]
Shape: (5,)
Size: 5
Data type : int64
Number of dimensions: 1
[[0.49305287 0.59553372 0.58399102]
 [0.49283937 0.17086651 0.70664143]
 [0.41977627 0.69971982 0.65604144]]
Shape: (3, 3)
Size: 9
Data type : float64
Number of dimensions: 2
adding 5 to each element of array [10 20 30 40 50]:
 [15 25 35 45 55]


In [14]:
a=np.array([[1,2,3],[4,5,6],[3,6,7]])
b=np.array([[7,8,9],[1,9,2],[4,6,8]])
print(a)
print(b)
print(a*b)

[[1 2 3]
 [4 5 6]
 [3 6 7]]
[[7 8 9]
 [1 9 2]
 [4 6 8]]
[[ 7 16 27]
 [ 4 45 12]
 [12 36 56]]


In [20]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("First Row:\n",a[0])
lst_col=a[:,-1]
print("Last Column:")
print(lst_col)

First Row:
 [1 2 3 4 5]
Last Column:
[ 5 10 15 20 25]


In [21]:
arr = np.arange(1, 26).reshape(5, 5)
print(arr)
first_row = arr[0]
print("The first row is ",first_row)
last_col=arr[:,-1]
print("The last column is:",last_col)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
The first row is  [1 2 3 4 5]
The last column is: [ 5 10 15 20 25]


In [24]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
print("maximum:",np.max(arr))

maximum: 100
